name: pushly_pushsdk
description: Flutter implementation of the Pushly PushSDK
version: 1.1.0
homepage: https://pushly.com

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.pushly.pushsdk
        pluginClass: PushsdkPlugin
      ios:
        pluginClass: PushlyPlugin
